// Generated by gencpp from file joy_andro/JoyAndro.msg
// DO NOT EDIT!


#ifndef JOY_ANDRO_MESSAGE_JOYANDRO_H
#define JOY_ANDRO_MESSAGE_JOYANDRO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace joy_andro
{
template <class ContainerAllocator>
struct JoyAndro_
{
  typedef JoyAndro_<ContainerAllocator> Type;

  JoyAndro_()
    : header()
    , x(0.0)
    , y(0.0)
    , button_x(false)
    , button_circle(false)
    , button_triangle(false)
    , button_square(false)  {
    }
  JoyAndro_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , button_x(false)
    , button_circle(false)
    , button_triangle(false)
    , button_square(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef uint8_t _button_x_type;
  _button_x_type button_x;

   typedef uint8_t _button_circle_type;
  _button_circle_type button_circle;

   typedef uint8_t _button_triangle_type;
  _button_triangle_type button_triangle;

   typedef uint8_t _button_square_type;
  _button_square_type button_square;





  typedef boost::shared_ptr< ::joy_andro::JoyAndro_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::joy_andro::JoyAndro_<ContainerAllocator> const> ConstPtr;

}; // struct JoyAndro_

typedef ::joy_andro::JoyAndro_<std::allocator<void> > JoyAndro;

typedef boost::shared_ptr< ::joy_andro::JoyAndro > JoyAndroPtr;
typedef boost::shared_ptr< ::joy_andro::JoyAndro const> JoyAndroConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::joy_andro::JoyAndro_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::joy_andro::JoyAndro_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::joy_andro::JoyAndro_<ContainerAllocator1> & lhs, const ::joy_andro::JoyAndro_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.button_x == rhs.button_x &&
    lhs.button_circle == rhs.button_circle &&
    lhs.button_triangle == rhs.button_triangle &&
    lhs.button_square == rhs.button_square;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::joy_andro::JoyAndro_<ContainerAllocator1> & lhs, const ::joy_andro::JoyAndro_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace joy_andro

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::joy_andro::JoyAndro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joy_andro::JoyAndro_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joy_andro::JoyAndro_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joy_andro::JoyAndro_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joy_andro::JoyAndro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joy_andro::JoyAndro_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::joy_andro::JoyAndro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4772fa7b3815bf94f88ced97e695f175";
  }

  static const char* value(const ::joy_andro::JoyAndro_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4772fa7b3815bf94ULL;
  static const uint64_t static_value2 = 0xf88ced97e695f175ULL;
};

template<class ContainerAllocator>
struct DataType< ::joy_andro::JoyAndro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joy_andro/JoyAndro";
  }

  static const char* value(const ::joy_andro::JoyAndro_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::joy_andro::JoyAndro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 x\n"
"float32 y\n"
"bool button_x\n"
"bool button_circle\n"
"bool button_triangle\n"
"bool button_square\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::joy_andro::JoyAndro_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::joy_andro::JoyAndro_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.button_x);
      stream.next(m.button_circle);
      stream.next(m.button_triangle);
      stream.next(m.button_square);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JoyAndro_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::joy_andro::JoyAndro_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::joy_andro::JoyAndro_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "button_x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.button_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "button_circle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.button_circle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "button_triangle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.button_triangle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "button_square: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.button_square);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOY_ANDRO_MESSAGE_JOYANDRO_H
